// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibidshfenfnlkizfgcvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliaWRzaGZlbmZubGtpemZnY3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxMTM4NjEsImV4cCI6MjA1MjY4OTg2MX0.ocosIKB5MP_EhPpwY0NGzZI5dMQEPj8TrM5_G177qQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);